server:
  port: 8081
  servlet:
    context-path: /userPortal
spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/ead5
    username: root
    password: admin
    driver-class-name : com.mysql.cj.jdbc.Driver
  mvc:
   view:
    prefix: /WEB-INF/pages/
    suffix: .jsp
   

